production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/swapeet-production

development:
  solr:
    hostname: localhost
    port: 8502
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
