production:
  solr:
    hostname: localhost
    port: 8502
    log_level: WARNING
    data_path: /home/wwwnewtone/newtone.name/shared/solr

development:
  solr:
    hostname: localhost
    port: 8502
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8502
    log_level: WARNING
