production:
  solr:
    hostname: localhost
    port: 8502
    log_level: WARNING
    data_dir: /home/wwwnewtone/newtone.name/shared/solr/data
    pid_dir: /home/wwwnewtone/newtone.name/shared/solr/pids

development:
  solr:
    hostname: localhost
    port: 8502
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8502
    log_level: WARNING
